# Generated by Django 2.2.5 on 2019-12-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('spotify_user_id', models.CharField(max_length=50)),
            ],
        ),
    ]
